apiVersion: v1
kind: Service
metadata:
  name: {{- include "eric-oss-porter-service-communication-name" . | indent 4 }}
  labels:
    {{- include "eric-oss-porter-service-communication.labels" . | indent 4 }}
  annotations:
{{- include "eric-oss-porter-service.annotations" . | indent 4 }}
spec:
  type: {{ .Values.service2.type }}
{{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
{{- end }}
  loadBalancerIP: {{ .Values.service2.LoadBalancerIP }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: eric-oss-porter-communications
    app.kubernetes.io/instance: {{ .Release.Name }}
