#
# COPYRIGHT Ericsson 2021
#
# The copyright to the computer program(s) herein is the property of
# Ericsson Inc. The programs may be used and/or copied only with written
# permission from Ericsson Inc. or in accordance with the terms and
# conditions stipulated in the agreement/contract under which the
# program(s) have been supplied.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-porter-service.name" . }}-app-configmap
  labels:
    app: {{ template "eric-oss-porter-service.name" . }}
    chart: {{ template "eric-oss-porter-service.chart" . }}
{{- include "eric-oss-porter-service.labels" . | nindent 4 }}
  annotations:
{{- include "eric-oss-porter-service.annotations" . | nindent 4 }}
data:
  data.conf: |
    DB_NAME: {{ .Values.database.name }}
    DB_HOST: {{ .Values.database.host | quote }}
    DB_PORT: {{ .Values.database.port | quote }}
    DB_USER: {{ .Values.database.user }}
    DB_PASSWORD: {{ .Values.database.password }}
    CONNECT_AFTER: {{ .Values.database.timeout }}
    CONNECT_REATTEMPTS: {{ .Values.database.retries }}
