{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
   name: {{ include "eric-oss-porter-service.name" . }}-default-deny-ingress
   labels:
    {{- include "eric-oss-porter-service.labels" . | indent 4 }}
   annotations:
     {{- include "eric-oss-porter-service.annotations" . | indent 4 }}
spec:
   podSelector: {}
   policyTypes:
   - Ingress
{{- end }}
{{- end }}
{{- end }}