{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eric-oss-porter-service.name" . }}-postgres-policy
  labels:
    {{- include "eric-oss-porter-service.labels" . | indent 4 }}
  annotations:
{{- include "eric-oss-porter-service.annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: eric-oss-porter-postgres
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
              app.kubernetes.io/name: eric-oss-porter-usermanagement
      - podSelector:
          matchLabels:
              app.kubernetes.io/name: eric-oss-porter-restsimofferings
      - podSelector:
          matchLabels:
              app.kubernetes.io/name: eric-oss-porter-communications
      ports:
      - port: 5432
        protocol: TCP
{{- end }}
{{- end }}
{{- end }}
