apiVersion: v1
data:
  custom-pwd: cmVzdHNpbQ==
  custom-user: cmVzdHNpbQ==
  metrics-pwd: cmVzdHNpbQ==
  replica-pwd: cmVzdHNpbQ==
  replica-user: cmVzdHNpbQ==
  super-pwd: cmVzdHNpbQ==
kind: Secret
metadata:
  name: eric-oss-porter-postgres-pg-secret
  labels:
{{- include "eric-oss-porter-service.labels" . | indent 4 }}
  annotations:
{{- include "eric-oss-porter-service.annotations" . | indent 4 }}