apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-oss-porter-service.name" . }}
  labels: {{- include "eric-oss-porter-service.labels" . | trim | nindent 4 }}
  annotations: {{- include "eric-oss-porter-service.annotations" . | trim | nindent 4 }}
automountServiceAccountToken: false