apiVersion: v1
kind: Service
metadata:
  name: {{- include "eric-oss-porter-service-usermanagement-name" . | indent 4 }}
  labels:
    {{- include "eric-oss-porter-service-usermanagement.labels" . | indent 4 }}
  annotations:
{{- include "eric-oss-porter-service.annotations" . | indent 4 }}
spec:
  type: {{ .Values.service1.type }}
{{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
{{- end }}
  loadBalancerIP: {{ .Values.service1.LoadBalancerIP }}
  ports:
    - port: {{ .Values.service1.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: eric-oss-porter-usermanagement
    app.kubernetes.io/instance: {{ .Release.Name }}